name: py

on:
  pull_request:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install looker-sdk
      - name: execute py script # run the run.py to get the latest data
        run: |
          python .github/workflows/prod_cicd.py
        env:
          LOOKERSDK_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          LOOKERSDK_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          LOOKERSDK_BASE_URL: 'https://prod.looker.looker-plus.com'
          LOOKERSDK_VERIFY_SSL: 'False'
          LOOKERSDK_API_VERSION: '4.0'
          LOOKERSDK_TIMEOUT: "120"
